In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("weatherPrediction2.csv")

In [3]:
data

     Outlook Temperature Humidity  Wind speed Play cricket
0      Sunny         NaN     High         4.0           No
1      Sunny         NaN     High        20.0           No
2   Overcast         Hot     High         6.0          Yes
3       Rain        Mild     High         2.0          Yes
4       Rain        Cool   Normal         7.0          Yes
5       Rain         NaN   Normal         NaN           No
6   Overcast        Cool   Normal        22.0          Yes
7      Sunny         NaN     High         4.0           No
8      Sunny        Cool   Normal         5.0          Yes
9       Rain        Mild   Normal         6.0          Yes
10     Sunny        Mild   Normal         NaN          Yes
11  Overcast        Mild     High         2.0          Yes
12  Overcast         NaN   Normal         8.0          Yes
13      Rain        Mild     High        18.0           No

In [4]:
# Điền median cho cột Wind Speed và mode cho cột Temperature
values = {'Temperature': data['Temperature'].mode()[0],
          'Wind speed': data['Wind speed'].median()}

data.fillna(value=values, inplace=True)

In [5]:
data

     Outlook Temperature Humidity  Wind speed Play cricket
0      Sunny        Mild     High         4.0           No
1      Sunny        Mild     High        20.0           No
2   Overcast         Hot     High         6.0          Yes
3       Rain        Mild     High         2.0          Yes
4       Rain        Cool   Normal         7.0          Yes
5       Rain        Mild   Normal         6.0           No
6   Overcast        Cool   Normal        22.0          Yes
7      Sunny        Mild     High         4.0           No
8      Sunny        Cool   Normal         5.0          Yes
9       Rain        Mild   Normal         6.0          Yes
10     Sunny        Mild   Normal         6.0          Yes
11  Overcast        Mild     High         2.0          Yes
12  Overcast        Mild   Normal         8.0          Yes
13      Rain        Mild     High        18.0           No